
redis:
  host: localhost
  port: 6379
  password: ''
  host-server: "SyncHost/01" #name of this server host

database:
  enable: false
  host: localhost
  port: 3306
  dbTable: xscasino
  user: root
  password: password

config:
  prizeTime: "20:00" #real time
  lockPrize: -1
  lockPrizeSetter: ""

cross-server:
  servers:
    - "Sync/01"
    - "Sync/02"